### PR TITLE
Fix test expectations on helper output 

### PR DESCRIPTION
**Pull request by Slamdunk**
Has anyone any idea why the build now fails without this fix?

### CODE REVIEW

**Comment by Slamdunk** [comment]
Ping @bakura10 @mimmi20

**Comment by Ocramius** [comment]
Hmm, how did we miss this before? :thinking:

**Review by Ocramius — APPROVED** [review]

**Comment by mimmi20** [comment]
> Has anyone any idea why the build now fails without this fix?

Any changes in ghcr.io/laminas/laminas-continuous-integration?

**Comment by Slamdunk** [comment]
Build was ok 2 weeks ago: https://github.com/laminas/laminas-form/actions/runs/3249434125/jobs/5331832262

WTF happened?

**Comment by Ocramius** [comment]
@Slamdunk can you perhaps try a bisect against the last green release?

**Comment by Slamdunk** [comment]
Easy one, look at https://github.com/laminas/laminas-form/commits/3.5.x only https://github.com/laminas/laminas-form/pull/195 have been merged, so the answer is nothing has changed.

Testing environment must have changed :open_mouth:

**Comment by Ocramius** [comment]
Yeah, but careful about linear history: we may have older commits dragged in by a merge.

**Comment by Slamdunk** [comment]
I reverted my code till https://github.com/laminas/laminas-form/commit/cd3f9d3e345b075d34793e46b0759a4dfd12f674, the merge commit for https://github.com/laminas/laminas-form/pull/184, and it's failing locally.

So, as far as I can tell, not a code issue but rather a testing environment change

**Comment by Ocramius** [comment]
The test environment did change, but the patch by @froschdesign was still green (yesterday?):

 * 9 days ago: https://github.com/laminas/laminas-continuous-integration-action/releases/tag/1.27.0
 * over a month ago: https://github.com/laminas/laminas-continuous-integration-action/releases/tag/1.26.0

**Comment by Slamdunk** [comment]
The patch over MD files doesn't trigger the PHP builds.

My best bet is that some patch landed over ICU depenency graph within Linux ecosystem, that adjusted `es_CL` `IntlDateFormatter::SHORT` from `dd-MM-yy HH:ii` (without comma) to `dd-MM-yy, HH:ii` (with comma).

Let's consider the case solved, and go on with our lives.

**Pull request merged**
