### PR TITLE
Move array values string type-casting out of the loop

### PR DESCRIPTION
**Pull request by pine3ree**
the array value type conversion should be done once

### CODE REVIEW

**Comment by Ocramius** [comment]
Inside strings, you are always dealing with FQNs for functions: no need for
`\\` :)
Marco Pivetta

***@***.***

https://ocramius.github.io/

**Comment by pine3ree** [comment]
Hello @Ocramius , 
do you wish me to add a commit for that? 
Or will you change it in a separate pr, that being not related?

kind regards

**Comment by Ocramius** [comment]
Please do push a new commit 😁

**Review by Ocramius — APPROVED** [review]
Thanks @pine3ree !

**Pull request merged**
