### PR TITLE
Conflict with laminas-code >= 4 to ensure BC

### PR DESCRIPTION
**Pull request by Slamdunk**
Fixes https://github.com/laminas/laminas-form/issues/100

### CODE REVIEW

**Comment by Ocramius** [comment]
Note that this will only prevent `2.16.3` to be installed, while `2.16.2` is still installable

**Comment by Slamdunk** [comment]
Sure, but at least I can say `2.16.3` "fixes" the issue :|
The same goes for https://github.com/laminas/laminas-form/pull/96
I had no other arrows on my quiver

**Comment by Ocramius** [comment]
@Slamdunk you did all that is possible, no worries: I was mostly leaving a bradcrumb for people encountering this :-)

**Comment by driehle** [comment]
@Slamdunk @Ocramius I disagree that this solves #100. For now, if your application requires laminas-code ^4.0 for some other reasons, compose will simply downgrade laminas-form to 2.16.2. That cannot be a solution, can it? I'd agree that this would be a solution if you'd remove 2.16.1 and 2.16.2 from packagist.

Moreover, I am am concerned if adding a conflict to laminas-code >= 4.0 is desirable at all. I'm having the issue that doctrine/migrations has a dependency (via friendsofphp/proxy-manager-lts) to laminas-code. So for all people that do not need laminas-code with laminas-form (because they don't use annotations), but who require laminas-code for other reasons, you are blocking the upgrade path.

**Comment by Ocramius** [comment]
@driehle it does what's possible: that's sadly how i works with too permissive dependency ranges.

That's what https://github.com/laminas/laminas-form/pull/101#issuecomment-814743995 was about.

The issue is indeed solved to the best extent we could handle it.

Alternatively, a better fix is to release `2.17.0` with support for `^4` too, and a wider dependency range.

As for `friendsofphp/proxy-manager-lts`, I cannot speak for that: their maintenance policy is questionable from my PoV.

**Comment by driehle** [comment]
@Ocramius see my proposal in #104 for supporting `laminas-code:^4.0` :-)

**Pull request merged**
