### PR TITLE
Apply PHP 7.4 syntax and typed property

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 7.4, php 7.4 syntax can be applied with typed properties. 

- For `final class`, typed properties for protected is allowed if no inherit of parent or used by its final class parent.
- Otherwise, update only private properties.

### CODE REVIEW

**Comment by Ocramius** [comment]
Looks like you ran PHPCS on 8.x :D

**Comment by samsonasik** [comment]
Yes, rolling back https://github.com/laminas/laminas-form/pull/183/commits/9c30a918f25d37f0727307069fb3e08c81261e41

**Comment by Ocramius** [comment]
@samsonasik please try explaining what you are doing, in the commit messages (applies here and in general)

**Comment by samsonasik** [comment]
I can squash commit after fixing cs

**Comment by samsonasik** [comment]
@Ocramius commits squashed, the PR do:

- apply php 7.4 typed properties
- apply php 7.4 syntaxes

**Comment by samsonasik** [comment]
All green 🎉

**Review by Ocramius — APPROVED** [review]
Awesome, thanks @samsonasik!

**Pull request merged**
