### PR TITLE
Add support for PHP 8.1, drop PHP 7.3

### LINKED ISSUE #151: PHP 8.1: Incompatibility with `IteratorAggregate::getIterator`
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary

The `Fieldset` implementation has an incompatibility with the `IteratorAggregate::getIterator`.

#### Current behavior

Tests are failing.
```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Return type of Fieldset::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice``
```

#### How to reproduce

Execute tests with PHP 8.1

#### Expected behavior

Tests are passing.

### PR DESCRIPTION
**Pull request by tobias-trozowski**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
Adding support for PHP 8.1

Related to https://github.com/laminas/laminas-form/issues/151

### CODE REVIEW

**Comment by Slamdunk** [comment]
I'll try to take care of this on Tuesday: if you are able to fix everything before that time, it would be awesome 👍

**Comment by tobias-trozowski** [comment]
not right sure what to do with the psalm error here as it also fails on 3.1.x

```
root@86e7d6d266e7:/app# vendor/bin/psalm --debug
Scanning files...
Registering autoloaded files
[... snip ...]
Using reflection to locate file for Zend\Validator\DateStep
Using reflection to locate file for Zend\Validator\Date
Using reflection to locate file for Zend\I18n\Validator\DateTime
Using reflection to locate file for Zend\Validator\Db\NoRecordExists
Fatal error: Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /app/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 29
```

**Comment by tobias-trozowski** [comment]
Tests for 8.1 should run once https://github.com/laminas/laminas-filter/issues/34 is done

**Comment by Slamdunk** [comment]
Thank you very much @tobias-trozowski

**Pull request merged**
