### PR TITLE
Allow PHP 8.4

### PR DESCRIPTION
**Pull request by fezfez**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

- composer bump --dev-only
- psalm baseline updated due to deprecated feature

### CODE REVIEW

**Comment by gsteel** [comment]
I'm reluctant to baseline all the deprecations from laminas-validator. Dealing with them now will make upgrading to v3, when it gets released, a lot easier. Merging this PR will mute all those issues…
🤔

**Comment by Xerkus** [comment]
php 8.4 CANNOT be declared compatible while it is in alpha.

**Comment by fezfez** [comment]
> php 8.4 CANNOT be declared compatible while it is in alpha.

I've seen that the job has begun https://github.com/orgs/laminas/projects/37 maybe it's unclear inside the laminas maintener community?

**Comment by fezfez** [comment]
> I'm reluctant to baseline all the deprecations from laminas-validator. Dealing with them now will make upgrading to v3, when it gets released, a lot easier. Merging this PR will mute all those issues… 🤔

Maybe you should create a 4.0.x branch with the 3.21.x before merging?

**Comment by Xerkus** [comment]
PHP 8.4 is in **alpha** release.  It can introduce incompatibilities or even BC breaks. It happened before.
Releases with PHP 8.4 added to the range will become incompatible in such occurrence but it is impossible to retroactively  change the range for past releases.

**Comment by fezfez** [comment]
According to https://php.watch/rfcs and https://wiki.php.net/todo/php84

The feature freeze is on 13 august, only two RFCs can be merge for 8.4 and none of them can lead to breaking the package, otherwise I understand that's waiting 10 day before merging is not a big deal 👍

Edit : php.watch same to not be up to date, more rfcs can be merge in 8.4 according to https://wiki.php.net/rfc

**Comment by Xerkus** [comment]
PRs are desirable to highlight any coming issues as well as patches dealing with future compat.

It's the releasing with 8.4 that is premature. Ideally we would want to wait for rc which is in about a month

**Comment by fezfez** [comment]
@Xerkus RC is out but the build is always with alpha, is there something to be done?

**Comment by froschdesign** [comment]
I have re-run all jobs, but the alpha version is still being used. 🤷🏻‍♂️ 

--- 

I have fixed the problems in the documentation: #278

**Comment by fezfez** [comment]
@froschdesign it's rc1 now :)

**Review by froschdesign — APPROVED** [review]

**Comment by froschdesign** [comment]
@fezfez 
Thank you for your time and this contribution! 👍

**Comment by Xerkus** [comment]
> [Merge branch 'laminas:3.21.x' into php8.4](https://github.com/laminas/laminas-form/pull/275/commits/d2c11882d6fe547c7d6217961fbc0469db3fbb34)

@fezfez  Please use rebase

**Comment by froschdesign** [comment]
The topic can be found in the contributing guidelines: [Keeping Up-to-Date](https://github.com/laminas/.github/blob/a5f819c70aa3a7f91ab75a612314be8cbb240168/CONTRIBUTING.md#keeping-up-to-date).

**Pull request merged**
