### PR TITLE
QA: Removes redundant conditions

### PR DESCRIPTION
**Pull request by michalbundyra**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

`setOptions` and `setAttributes` require `array|Traversable` and `ArrayAccess` is not allowed.

### CODE REVIEW

**Comment by froschdesign** [comment]
@michalbundyra 
> …ArrayAccess is not allowed.

It is listed in the related DocBlock:

https://github.com/laminas/laminas-form/blob/64fe229a952c86c9145a84e5662e91cf926632a7/src/Factory.php#L185-L200

**Comment by michalbundyra** [comment]
@froschdesign 

> It is listed in the related DocBlock

Right, but for `$spec` not, `$spec['attributes']` or `$spec['options']`.

See also:
https://github.com/laminas/laminas-form/blob/64fe229a952c86c9145a84e5662e91cf926632a7/src/ElementInterface.php#L31-L37
https://github.com/laminas/laminas-form/blob/64fe229a952c86c9145a84e5662e91cf926632a7/src/ElementInterface.php#L88-L96

And our implementation:
https://github.com/laminas/laminas-form/blob/64fe229a952c86c9145a84e5662e91cf926632a7/src/Element.php#L112-L124

**Comment by froschdesign** [comment]
@michalbundyra 
I know the underlying definitions and the comments in #55 but I mean these lines:

https://github.com/laminas/laminas-form/blob/64fe229a952c86c9145a84e5662e91cf926632a7/src/Factory.php#L188-L193

**Comment by michalbundyra** [comment]
@froschdesign thanks, nice catch - PHPDocs updated now.

**Comment by froschdesign** [comment]
@michalbundyra 
Sorry for the misunderstanding which is based on my very short comment.

**Pull request merged**
